#!/usr/bin/env bash
# configure Nginx server
sudo sed -i '/server_name _;/a \location /redirect_me {\n return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n}' /etc/nginx/sites-availabe/default
sudo service nginx restart
