#!/usr/bin/env bash
# Configures an Ubuntu server as follows:
#   - localhost resolves to 127.0.0.2
#   - facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.active
echo "127.0.0.2		localhost" > ~/hosts.active
echo "8.8.8.8		facebook.com" >> ~/hosts.active
cp -f ~/hosts.active /etc/hosts
